features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://ISU Library Logo_Left_red-500.png'
favicon:
  use_default: 1
lib_navbar: 1
