features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://ISU Library Logo_Left_red-500.png'
favicon:
  use_default: 1
lib_navbar: 1
lib-util-nav1-text: 'Staff Directory'
lib-util-nav1-url: 'http://drupalvm.test/staff-directory'
lib_util_nav1_text: Directory
lib_util_nav1_url: 'http://drupalvm.test/staff-directory'
lib_util_nav2_text: Departments
lib_util_nav2_url: 'http://drupalvm.test/node/5'
lib_util_nav3_text: ''
lib_util_nav3_url: ''
lib_util_nav4_text: ''
lib_util_nav4_url: ''
lib_util_nav5_text: ''
lib_util_nav5_url: ''
